---
- name: update package cache
  apt:
    update_cache: yes
    force_apt_get: yes
  become: yes

- name: install ansible dependencies
  apt:
    name: software-properties-common
    state: present
  become: yes

- name: set up ansible ppa
  apt_repository:
    repo: ppa:ansible/ansible
  become: yes

- name: installs ansible
  apt:
    name: ansible
    state: present
  become: yes

- name: allows system agents to sudo without password
  group:
    name: system-agent
    state: present
    system: yes
  become: yes

- name: adds sudoers file
  copy:
    src: sudoers
    dest: /etc/sudoers
  become: yes

- name: creates system_agent users
  user:
    name: '{{ item.name }}'
    group: system-agent
    system: yes
    generate_ssh_key: yes
    update_password: on_create
  with_items: '{{ system_agents }}'

- name: setup ssh config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
  become: yes

- name: adds admin users with default password
  user:
    name: '{{ item.name }}'
    password: '{{ item.password }}'
    groups:
      - sudo
      - adm
      - admin
      - lxd
  with_items: '{{ admin_users }}'
  when: (admin_users | length > 0)
  become: yes

- name: adds authorized key for each admin_user
  authorized_key:
    user: '{{ item.name }}'
    key: "{{ lookup('file', item.pubkey_file) }}"
    state: present
  with_items: '{{ admin_users }}'
  become: yes
