---
- name: update package cache
  apt:
    update_cache: yes
    force_apt_get: yes
  become: yes

- name: upgrade packages
  apt:
    upgrade: dist
    force_apt_get: yes
  become: yes

- name: setup ssh config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
  become: yes

- name: adds admin users with default password
  user:
    name: '{{ item.name }}'
    password: '{{ item.password }}'
    groups:
      - sudo
      - adm
      - admin
      - lxd
  with_items: '{{ admin_users }}'
  when: (admin_users | length > 0)
  become: yes

- name: adds authorized key for each admin_user
  authorized_key:
    user: '{{ item.name }}'
    key: "{{ lookup('file', item.pubkey_file) }}"
    state: present
  with_items: '{{ admin_users }}'
  become: yes
