---
- name: Converge
  hosts: all
  pre_tasks:
    - name: creates groups used in the role
      group:
        name: '{{ item }}'
        state: present
      with_items:
        - admin
        - adm
        - lxd
      become: yes

    - name: ensures right mode on ssh key files
      file:
        path: files
        state: directory
        mode: g-rwx,o-rwx
        recurse: yes
      delegate_to: localhost

  roles:
    - role: ansible-role-users
      admin_users:
        - name: controller_admin
          password: $6$salagosto$24o95HxJaaU/e/jb8sMoIUsa6HtLw/N7Ha5BxJ1XgDXZJLMjyKx9EGiAWrgdLoAWjVgBCuwME1URqoz9fu4oh/
          pubkey_file: files/controller_admin.pub
      controller_clients:
        - name: alice
          pubkey_file: files/alice.pub
        - name: bob
          pubkey_file: files/bob.pub
      system_agents:
        - name: controller_agent

  tasks:
    - name: starts ssh
      service:
        name: ssh
        state: started
